### ISSUE TITLE
Error when running sanity graphql deploy

### ISSUE THREAD

**Issue by chanmathew** [good-idea/sane-shopify#36] opened 2020-01-16 23:26 UTC
Hey Joseph,

So I tried removing and reinstalling node modules and I'm still getting this error on 0.6.3:

```
✖ Generating GraphQL schema
/Users/mathew/Dev/esqido-gatsby-sanity/studio/node_modules/@sane-shopify/sanity-plugin/lib/index.js:1
import { createElement, createContext, Component, useContext, Fragment } from 'react';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at Object.<anonymous> (~/Dev/esqido-gatsby-sanity/studio/schemas/schema.js:4:1)
```

Here's my schema.js:
```
import createSchema from 'part:@sanity/base/schema-creator'
import schemaTypes from 'all:part:@sanity/base/schema-type'

import {
  createProductDocument,
  createCollectionDocument,
  saneShopifyObjects,
} from '@sane-shopify/sanity-plugin'

const product = createProductDocument({
  fields: [
    {
      title: 'Tags',
      name: 'tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags',
      },
    },
  ],
})
const collection = createCollectionDocument()

export default createSchema({
  name: 'mySchema',
  types: schemaTypes.concat([...saneShopifyObjects, product, collection]),
})
```

**Comment by good-idea** [comment] 2020-01-17 22:27
Ugh! Thanks for sticking through all of these bugs. I just published `@sane-shopify/sanity-plugin 0.6.5`, i *think* it will work.

This was caused by my fumbling with the rollup config -- it was being published only as an es module (which uses `import`) and not a normal cjs module (which uses `require`).

What I don't understand is why it was working for me this way, but not for you. What version of node are you using?

**Comment by chanmathew** [comment] 2020-01-17 22:33
No worries! I'm on node 12.13.1. Just upgraded to 0.6.5, now I'm getting this:

```
✖ Generating GraphQL schema
/Users/mathew/Dev/esqido-gatsby-sanity/studio/node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^
SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at Object.<anonymous> (~/Dev/esqido-gatsby-sanity/studio/node_modules/@sane-shopify/sanity-plugin/lib/index.js:6:16)
```

**Comment by good-idea** [comment] 2020-01-17 22:47
ugh! the same issue but now with a package that isn't mine. Would you be able to share the repository with me?

**Comment by chanmathew** [comment] 2020-01-17 22:52
Haha sorry for the trouble! Just sent you a collaborator invite to my repo.

**Comment by good-idea** [comment] 2020-01-18 00:03
Weird, it's all working for me. For some reason, it seems like on your end, the `sanity` commands are not using babel to transpile the ES modules.

Some more questions:

- do your `dev`, `build`, and `test` scripts work?
- can you clone [this repo](https://github.com/good-idea/test-sanity-studio) and try `npm run start` and `npm run graphql-deploy`? (You may need to swap out your projectId in sanity.json to deploy)

**Comment by chanmathew** [comment] 2020-01-18 23:54
> Weird, it's all working for me. For some reason, it seems like on your end, the `sanity` commands are not using babel to transpile the ES modules.
> 
> Some more questions:
> 
> * do your `dev`, `build`, and `test` scripts work?
> * can you clone [this repo](https://github.com/good-idea/test-sanity-studio) and try `npm run start` and `npm run graphql-deploy`? (You may need to swap out your projectId in sanity.json to deploy)

hey Joseph the repo looks like it's empty? 

Yes I tried both `dev` and `build` and they all work, also upgraded to 0.6.8.

However when I run `test` I run into this error:
```
Error:  * Part "part:@sanity/form-builder/input/shopifySelector/schema" was attempted to be implemented by "/Users/mathew/Dev/esqido-gatsby-sanity/studio/node_modules/@sane-shopify/sanity-plugin/lib/schema.js", which does not seem to exist. Check "@sane-shopify/sanity-plugin" and keep in mind that paths in Sanity are case-sensitive.
    at throwOnErrors (~/Dev/esqido-gatsby-sanity/studio/node_modules/@sanity/check/src/sanityCheck.js:47:17)
    at ~/Dev/esqido-gatsby-sanity/studio/node_modules/@sanity/check/src/sanityCheck.js:36:22
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sanity-studio@1.0.1 test: `sanity check`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sanity-studio@1.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by good-idea** [comment] 2020-01-20 23:17
Oh, heck, i forgot to push. Repo is now up. Sorry about that!

**Comment by chanmathew** [comment] 2020-01-21 04:22
> Oh, heck, i forgot to push. Repo is now up. Sorry about that!

No worries! Just tried it, it runs fine but still doesn't deploy graphql, getting this error:

```
✖ Generating GraphQL schema
/Users/mathew/Dev/test-sanity-studio/node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^
SyntaxError: Unexpected token 'export'
    at Object.<anonymous> (~/Dev/test-sanity-studio/node_modules/@sane-shopify/sanity-plugin/lib/index.js:6:16)
```

**Comment by good-idea** [comment] 2020-01-21 23:08
@homerjam , could you try running `sanity graphql deploy --playground` on one if your instances to see if this problem comes up for you?

**Comment by homerjam** [comment] 2020-01-23 10:28
Yes - can confirm, this happens for me too.

```
✖ Generating GraphQL schema
/Users/jameshomer/Documents/projects/glassworks/sanity/node_modules/@sane-shopify/sanity-plugin/lib/index.js:1
import { createElement, createContext, Component, useContext, Fragment } from 'react';
       ^
SyntaxError: Unexpected token {
    at Object.<anonymous> (~/Documents/projects/glassworks/sanity/schemas/schema.js:7:1)
```

**Comment by good-idea** [comment] 2020-01-25 23:39
I still have no idea why I can't reproduce this 🤷‍♂ but I swapped out the `lodash-es` for `lodash`.

Could you both give it another shot?

If it's still not working:
- Are you using a globally installed version of the sanity CLI?
- If so, could you try:
  - adding `@sanity/cli` as a devDependency
  - deploying via an NPM script, i.e. `"deploy": "sanity graphql deploy --playground"`
- Or, try updating your global sanity CLI?

Maybe using a `@sanity/cli` installed locally is the thing to do?

Anyways if this doesn't do the trick I'll just remove the ES module exports completely for now.

**Comment by chanmathew** [comment] 2020-01-26 02:29
Hey Joseph, thanks for the update.

So I just upgraded everything, removed node modules, did a fresh install, and I'm still getting this error, looks like it's still loading lodash-es?

```
✖ Generating GraphQL schema
/Users/mathew/Dev/esqido-gatsby-sanity/studio/node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^
SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at Object.<anonymous> (~/Dev/esqido-gatsby-sanity/studio/node_modules/@sane-shopify/sanity-plugin/lib/index.js:6:16)
```

Here's my package.json if it helps:
```
{
  "private": true,
  "name": "sanity-studio",
  "version": "1.0.1",
  "main": "package.json",
  "author": "Sanity <hello@sanity.io>",
  "scripts": {
    "dev": "sanity start",
    "format": "prettier-eslint --write \"**/*.js\" \"!node_modules/**\"",
    "build": "sanity build",
    "graphql-deploy": "sanity graphql deploy --playground",
    "lint": "eslint .",
    "test": "sanity check"
  },
  "dependencies": {
    "@sane-shopify/sanity-plugin": "^0.7.0",
    "@sanity/base": "^0.147.8",
    "@sanity/cli": "^0.147.8",
    "@sanity/components": "^0.147.9",
    "@sanity/core": "^0.147.9",
    "@sanity/dashboard": "^0.147.8",
    "@sanity/default-layout": "^0.147.9",
    "@sanity/default-login": "^0.147.0",
    "@sanity/desk-tool": "^0.147.9",
    "date-fns": "^1.30.1",
    "graphql": "^14.5.8",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "sanity-plugin-dashboard-widget-document-list": "^0.0.8",
    "sanity-plugin-dashboard-widget-netlify": "^1.0.1"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^6.9.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-config-standard-react": "^7.0.2",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-node": "^9.0.1",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-promise": "^4.1.1",
    "eslint-plugin-react": "^7.13.0",
    "eslint-plugin-standard": "^4.0.0",
    "prettier-eslint-cli": "^5.0.0"
  }
}
```

**Comment by good-idea** [comment] 2020-01-27 15:08
Oops, it looks like I didn't fully remove `lodash-es`. `0.7.1` did, but still includes es module exports, which may be the issue here. Let me know if that works, if not, I'll just remove es modules completely.

Also - in my search to try to reproduce this - could you create a repo for me?

**Comment by chanmathew** [comment] 2020-01-27 17:56
@good-idea It seems to be fixed in latest release! Do you still want me to create a repo?

**Comment by good-idea** [comment] 2020-01-27 18:00
yes please! I'll close this issue but I'd still like to try to reproduce this on my end

**Closed as completed by good-idea** 2020-01-27 18:00 UTC

**Comment by chanmathew** [comment] 2020-01-29 16:14
Hey @good-idea I've zipped up the whole repo for you, just removed the projectId:

[esqido-gatsby-sanity-dev.zip](https://github.com/good-idea/sane-shopify/files/4129119/esqido-gatsby-sanity-dev.zip)
